console.log("coucou depuis la console");

array = [
  "@jcunniet",
  "@PaulLampon",
  "@Aziliz31",
  "@ssoumier",
  "@marionsouzeau",
  "@gaellombart",
  "@bendarag",
  "@AurelieLebelle",
  "@julienduffe",
  "@thomaspoupeau",
  "@LilyRossignol",
  "@ClairGuedon",
  "@stephanieauguy",
  "@claw_prolongeau",
  "@_JulieMenard",
  "@LColcomb",
  "@Zlauwereys",
  "@MeLonguet",
  "@DorotheeLN",
  "@NolwennCosson",
  "@ADaboval",
  "@Remibaldy",
  "@bderveaux",
  "@amandechap",
  "@ELODIESOULIE",
  "@nbongarcon",
  "@HeloAb",
  "@Panamorama",
  "@gregplou",
  "@BenoitBerthe",
  "@LauraBruneau89",
  "@Anthony_Lieures",
  "@Sharonwaj",
  "@mcsonkin",
  "@pverduzier",
  "@emiliel3",
  "@Julien_MARION",
  "@SophiFay",
  "@bdelombre",
  "@annalecerf",
  "@AdriaBudry",
  "@DejNikolic",
  "@iJaffre",
  "@CyrusleVirus",
  "@GPardigon",
  "@e_vallerey",
  "@IsabelleSouquet",
  "@AudeDavidRossi",
  "@Yoann_Pa",
  "@CeliaPenavaire",
  "@perraultvincent",
  "@cboulate",
  "@JustineWeyl",
  "@Paulinejacot",
  "@juliechab",
  "@aslechevallier",
  "@phnou",
  "@Seb_Pommier",
  "@Alex_Bensaid",
  "@GuillaumeGaven",
  "@annelaurechouin",
  "@Oliviader",
  "@guerricp",
  "@JMMarchaut",
  "@cyceron",
  "@gregory_raymond",
  "@vhunsinger",
  "@l_peillon",
  "@fannyguinochet",
  "@EAssayag",
  "@KibweAdom",
  "@YvonHerry",
  "@JohanGarciajg",
  "@saidlabidi",
  "@lauranneprov",
  "@LeaDavy",
  "@francois_remy",
  "@CGuicheteau",
  "@FloMaillet",
  "@m_perroud",
  "@oBrunet_TSMF",
  "@MoonVdc",
  "@jc2taille",
  "@NellyMoussu",
  "@VirginK",
  "@b_misa",
  "@FabriceCouste",
  "@barbara_prose",
  "@lelia2m",
  "@brunoaskenazi",
  "@laurenechamp",
  "@ysisbox",
  "@juliengagliardi",
  "@PierreLel",
  "@kdeniau",
  "@_TerraInc",
  "@DominicArpin",
  "@antoinfonteneau",
  "@nanotousch",
  "@jb_roch",
  "@YaniKhezzar",
  "@Anne_Bechet",
  "@NCapart",
  "@SamyBenNaceur",
  "@Joumany",
  "@Julietteraynal",
  "@TGiraudet",
  "@SaraTanit",
  "@HappeFrederic",
  "@antoinellorca",
  "@michelpicot",
  "@Sev_Ryne",
  "@bobdobolino",
  "@murdever",
  "@YGrandmontagne",
  "@Mnyo",
  "@EdKOSCIANSKI",
  "@tnoisette",
  "@jankari",
  "@delbello_rom",
  "@rflechaux",
  "@NadiaSorelli",
  "@IT_Digital",
  "@abarbaux",
  "@PhilippeLeroy",
  "@schaptal",
  "@marionspee",
  "@lisavignoli",
  "@ChloeAeberhardt",
  "@MartineJacot",
  "@JuliaPascualita",
  "@curieusedetout",
  "@sgraveleau",
  "@bif_o",
  "@ElisaPineau",
  "@zinebdryef",
  "@apiquard",
  "@pierrehaski",
  "@StephanieDelmas",
  "@Blandine_Garot",
  "@vergara_i",
  "@evan_lebastard",
  "@SophieVclt",
  "@OlivierLevrault",
  "@alicedorgeval",
  "@LouiseMalnoy",
  "@alix_fx",
  "@pierre_baudis",
  "@LucMagoutier",
  "@AgatheMuller",
  "@SGianninelli",
  "@PaulineBoyer33",
  "@NaomiHalll",
  "@romaindlx",
  "@marionbr",
  "@Burtschy",
  "@JacobEtienne",
  "@as_lizzani",
  "@marie_simon",
  "@LaureDaussy",
  "@FabriceAmedeo",
  "@LoubnaChlaikhy",
  "@PlummerWilliam",
  "@OlivierMarin1",
  "@alaurefremont",
  "@mwesfreid",
  "@ChBaDe",
  "@pmathon",
  "@theobaldmarie",
  "@Lnpagesy",
  "@marclandre",
  "@paoliniesther",
  "@Feertchak",
  "@JBLitzler",
  "@GuillaumeErrard",
  "@quentinperinel",
  "@TristanQM",
  "@mlbo",
  "@constancejamet",
  "@LoraTerrazas",
  "@emiliegeffray",
  "@Mathilde_Sd",
  "@CaroPiquet",
  "@DCanivez",
  "@TIM_7375",
  "@blandinelc",
  "@ivanrioufol",
  "@arthurberdah",
  "@SarahLecoeuvre",
  "@guillaume_gui",
  "@DamienMercereau",
  "@W_Chloe",
  "@Assma_MD",
  "@EugenieBastie",
  "@HiTech_lexpress",
  "@bcondominas",
  "@Laurie_Z_",
  "@jeanfrancgerard",
  "@MathieuPagura",
  "@BGUYF",
  "@AlainPiffaretti",
  "@AudreyKucinskas",
  "@julienhory",
  "@Pierrefalga",
  "@TiphThuillier",
  "@cdaniez",
  "@LigerBaptiste",
  "@D_Peras",
  "@julie_dlb",
  "@Fatiha_Temmouri",
  "@julian2lamancha",
  "@GaetaneDeljurie",
  "@JulianMattei",
  "@M_Vicuna",
  "@DeBruynOlivier",
  "@Nehed_Jendoubi",
  "@antoine_grenapi",
  "@ColonnaGen",
  "@VictoriaGairin",
  "@Clement_Lacombe",
  "@TVigoureux",
  "@MargauxObriot",
  "@solinedelos",
  "@RocheSabine",
  "@dangerkens",
  "@EdouardDutour",
  "@MDondeyne",
  "@DupuisNathalie1",
  "@bouscarel",
  "@Mathieu2jean",
  "@Sophie_T_J",
  "@laurentcalixte",
  "@patrockwilliams",
  "@PascaleKremer",
  "@AlexJaquin",
  "@LauraIsaaz",
  "@cath_robin",
  "@Del_Gautherin",
  "@Isaduriez",
  "@lucietuile",
  "@AugeyBastien",
  "@mcastagnet",
  "@AminaKalache",
  "@mvaudano",
  "@CParrot",
  "@ombelinetips",
  "@_JoinLion",
  "@BarbolosiRose",
  "@ToiBruno1",
  "@FloraClodic",
  "@xjbdx",
  "@AlexiaEy",
  "@Emjy_STARK",
  "@elcoco01",
  "@rabilebon",
  "@pflovens_",
  "@FabriceFrossard",
  "@MorganeSERRES",
  "@MarjolaineKoch",
  "@edgarsnow",
  "@SRNLF",
  "@CChassigneux",
  "@KerinecMoran",
  "@NassiraELM",
  "@NewsRicard",
  "@Sandreene",
  "@Emilezrt",
  "@Pierre_Do",
  "@Micode",
  "@CColumelli",
  "@DavidAbiker",
  "@ClementBergantz",
  "@benjaminrabier",
  "@celinekallmann",
  "@edwyplenel",
  "@C_Barbier",
  "@JJBourdin_RMC",
  "@LaurenceFerrari",
  "@aslapix",
  "@IsaMillet",
  "@MaximeSwitek",
  "@tomjoubert",
  "@jszanchi",
  "@roqueeva",
  "@XavierBiseul",
  "@florencesantrot",
  "@AntoineCrochet",
  "@freeman59",
  "@MaudeML",
  "@philippe_gulpi",
  "@mathieum76",
  "@kiouari",
  "@imanemoustakir",
  "@BenedicteMallet",
  "@Emilie_Brouze",
  "@antoinebarret",
  "@_nicolasbocquet",
  "@remibuhagiar",
  "@CourretB",
  "@AymericRobert",
  "@miraelmartins",
  "@pmaniere",
  "@jesuisraphk",
  "@David_Ingram",
  "@pcelerier",
  "@technomedia",
  "@Geraldinedauver",
  "@ThierryLabro",
  "@Newsdusud",
  "@nrauline",
  "@gbregeras",
  "@SCouasnonBFM",
  "@actualites_nrv",
  "@dimitrimoulins",
  "@oli_aura",
  "@FabieChiche",
  "@Vincent_Raimblt",
  "@ChristophGreuet",
  "@PAlbuchay",
  "@MarrauddesGrot",
  "@vtalmon",
  "@cedric",
  "@olivierfrigara",
  "@Julien_Jay",
  "@LydiaBerroyer",
  "@Shuua",
  "@datisdaz",
  "@Steuph",
  "@ameliecharnay",
  "@Bruno_LesNums",
  "@LelloucheNico",
  "@CciliaDiQuinzio",
  "@Elodie_C",
  "@SylvRolland",
  "@Kocobe",
  "@FL_Debes",
  "@jdupontcalbo",
  "@GarciaVictor_",
  "@NicoRichaud",
  "@RHoueix",
  "@simottel",
  "@DamienLicata",
  "@annabelle_L",
  "@Lea_Lejeune",
  "@axel_deb",
  "@marin_eben",
  "@ptiberry",
  "@MatthieuDelach",
  "@sandrinecassini",
  "@benjaminferran",
  "@ppgarcia75",
  "@NotPatrick",
  "@ivalerio",
  "@FabienneSchmitt",
  "@alexgoude",
  "@JeromeColombain",
  "@manhack",
  "@Capucine_Cousin",
  "@Fsorel",
  "@oliviertesquet",
  "@marjoriepaillon",
  "@ginades",
  "@PierreTran",
  "@DelphineCuny",
  "@reesmarc",
  "@lauratenoudji",
  "@ldupin",
  "@carolinedescham",
  "@Lucile_Quillet",
  "@cgabizon",
  "@Allocab",
  "@epenser",
  "@JAGventeprivee",
  "@frwrds",
  "@Laure__Bourdon",
  "@Xavier75",
  "@maximeverner",
  "@s_jourdain",
  "@LoriHelloc"
];

console.log("===================================================");

let sL = array.length;
console.log(`il y a ${sL} journalistes`)

console.log("===================================================");

let count = 0;
for (let i = 0; i < array.length; i++)
{
 if(array[i].match(/\d/)){ count++; }
}
console.log(`${count} comptes possedent un chiffre`);

console.log("===================================================");

const textFilter = (requete) => { 
  return array.filter(el =>  el.toLowerCase().indexOf(requete.toLowerCase()) > -1);
}

console.log(` il y a ${textFilter('aude').length} compte qui ont "aude"`);

console.log("===================================================");

let countMaj = 0
array.forEach(element => {
  
  let withoutA = element.slice(1);
  if (withoutA[0] === withoutA[0].toUpperCase()){countMaj++;}
  
});
console.log(`il y a ${countMaj} comptes qui ont une maj après le @`);

console.log("===================================================");

let totalMaj = 0
for (let e = 0; e < array.length; e++)
{
 if(array[e].match(/[A-Z]/g)){ totalMaj++; }
}
console.log(`${totalMaj} comptes possedent une Majuscule`);

console.log("===================================================");

function numberOf_(){
  let i = 0;
  substring = "_";
  array.forEach(journalist => {
    i += journalist.split("_").length-1;
  });
  console.log(`Le nombre de journalistes dont le handle contient un "_" est ${i}`);
 };

 console.log("===================================================");

 console.log(numberOf_());
 let arrayWithoutA = [];
 array.forEach(element => {
   
  let resultat = element.slice(1);
  arrayWithoutA.push(resultat);
  
  order = arrayWithoutA.sort();
});
console.log(order);

console.log("===================================================");

order.sort(function(a, b){
  return a.length - b.length;
});
console.log(order.slice(0,50));

console.log("===================================================");

const indice = array.findIndex(el => el === "@epenser");
console.log(`${array[indice]} est à la place ${(indice)} de l'array initial `);

